// 50+ honeypot routes: ban IP immediately, return plausible-looking decoy response.
// Must be registered AFTER CORS but BEFORE auth + real routes.

import type { MiddlewareHandler } from 'hono'
import { banIp, getClientIp } from './threatDetector'
import { trackSecurityEvent, getSecEnv, getExecCtx } from './securityCollector'

// O(1) exact-match honeypot paths
const EXACT = new Set([
  // WordPress
  '/wp-admin', '/wp-login.php', '/xmlrpc.php', '/wp-cron.php', '/wp-signup.php',
  // Secrets / config leaks
  '/.env', '/.env.local', '/.env.production', '/.env.backup', '/.env.example', '/.env.test', '/.env.staging',
  '/.git/config', '/.git/HEAD', '/.gitignore', '/.gitattributes',
  '/.ssh/authorized_keys', '/.ssh/id_rsa', '/.ssh/id_rsa.pub',
  '/.htaccess', '/.htpasswd',
  // PHP admin panels
  '/phpmyadmin', '/pma', '/phpMyAdmin', '/phpmyadmin/index.php', '/pma/index.php', '/dbadmin',
  // PHP web shells
  '/c99.php', '/r57.php', '/cmd.php', '/shell.php', '/webshell.php', '/b374k.php', '/alfa.php',
  '/adminer.php', '/adminer', '/p.php', '/web.config',
  // Database dumps
  '/backup.sql', '/dump.sql', '/db.sql', '/database.sql', '/mysql.sql',
  '/backup.zip', '/backup.tar.gz', '/site.zip', '/db.tar.gz', '/data.zip',
  // Spring Boot actuator
  '/actuator', '/actuator/env', '/actuator/health', '/actuator/mappings',
  '/actuator/beans', '/actuator/metrics', '/actuator/dump', '/actuator/trace', '/actuator/logfile',
  // Laravel
  '/telescope', '/horizon', '/_ignition/health-check', '/laravel-websockets',
  // Cloud metadata
  '/.aws/credentials', '/.aws/config', '/aws.yml',
  '/latest/meta-data/', '/latest/meta-data/iam/security-credentials/',
  // API documentation
  '/swagger', '/swagger-ui', '/swagger-ui.html', '/api-docs', '/api/swagger',
  '/swagger.json', '/openapi.json', '/v2/api-docs', '/v3/api-docs',
  // Server diagnostics
  '/server-status', '/server-info', '/nginx_status', '/phpinfo.php', '/info.php',
  // Admin panels
  '/admin', '/admin/login', '/administrator', '/admin.php',
  '/manager', '/console', '/control', '/panel',
  // Setup / install
  '/setup.php', '/install.php', '/install', '/upgrade.php', '/config.php',
  // Misc
  '/test.php', '/old.php', '/tmp', '/temp', '/bak',
])

// Wildcard prefix patterns
const PREFIX_RE = /^\/(wp-content\/|wp-includes\/|wp-json\/|wp-admin\/|phpmyadmin\/|pma\/|actuator\/|telescope\/|horizon\/api\/|latest\/meta-data\/|\.git\/|\.svn\/|\.hg\/|vendor\/phpunit|node_modules\/\.bin)/i

function isHoneypot(path: string): boolean {
  return EXACT.has(path) || PREFIX_RE.test(path)
}

// Rotating decoy bodies — varies by path to confuse automated diff analysis
const DECOY_HTML = '<!DOCTYPE html><html><head><title>Index of /</title></head><body><h1>Index of /</h1><hr><pre>../\n</pre><hr></body></html>'
const DECOY_PHP  = '<?php\n// Generated by WordPress\ndefine(\'DB_NAME\', \'wordpress\');\n'
const DECOY_JSON = '{"status":"success","version":"1.0.0","environment":"production"}'
const DECOY_CONF = '[core]\n\trepositoryformatversion = 0\n\tfilemode = false\n\tbare = false\n'

function decoyResponse(path: string): Response {
  if (path.includes('git'))     return new Response(DECOY_CONF, { status: 200, headers: { 'content-type': 'text/plain' } })
  if (path.endsWith('.php'))    return new Response(DECOY_PHP,  { status: 200, headers: { 'content-type': 'text/plain' } })
  if (path.endsWith('.json'))   return new Response(DECOY_JSON, { status: 200, headers: { 'content-type': 'application/json' } })
  return new Response(DECOY_HTML, { status: 200, headers: { 'content-type': 'text/html' } })
}

export const honeypotsMiddleware: MiddlewareHandler = async (c, next) => {
  if (!isHoneypot(c.req.path)) return next()

  const ip = getClientIp(c.req.raw)
  banIp(ip)
  trackSecurityEvent(
    'honeypot_triggered', 'critical',
    { ip, path: c.req.path, method: c.req.method },
    getSecEnv(c),
    getExecCtx(c),
  )

  return decoyResponse(c.req.path)
}
